# Generated by Django 4.2 on 2024-02-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Customer First name', max_length=54)),
                ('last_name', models.CharField(help_text='Customer Last name', max_length=54)),
                ('user_email', models.EmailField(help_text='Customer Email', max_length=254)),
                ('user_phone', models.EmailField(help_text='Customer Phone', max_length=254)),
                ('password', models.CharField(help_text='Password', max_length=544)),
            ],
        ),
    ]
